# config version
CONFIG_VERSION: 0.0.4

# token of the bot that's going to be used
bot_token: sample.bot_token

# bot's client ID.
client_id: place bot client ID here

# User ID of the owner
owner_id: 123456789

# Set the prefix of your command
trigger: ","

# Auto delete responses from MineCordBot Commands
auto_delete_command_response: true

# Auto update MineCordBot, to stay up to date
auto_update: true

# Bot's language. Available language: en(english)
language: en

# Text channel ID of the guild you want to bind to Minecraft
text_channels:
  - 9876543212
  - 9382382323

# ID's of people who has permissions to do MineCordBot commands
Permissions:
  level_1:
    - 193970511615623168
  level_2:
    - 231232321323123232
  level_3:
    - 323123232323231231

# message prefix that will be seen in Discord
message_prefix_discord: Minecraft

# message prefix that will be seen in minecraft. This support conventional Bukkit Formatting. i.e &6, &e, etc.
message_prefix_minecraft: Discord

# toggle different events to be broadcasted on discord
broadcast:
    death_event: true
    join_event: true
    leave_event: true
    hide_user_with_incognito_perm: false
