name: MineCordBot
version: Minecordbot v1.0.1
author: CyRien
description: Discord bot that bridge chat from minecraft to discord

main: us.cyrien.MineCordBotV1.main.MineCordBot

commands:
    minecordbot:
        description: MineCordBot general commands
        usage: /CFA <command>
permmission:
    minecordbot.reload:
        default: op