name: MineCordBot
version: 1.0.3
author: CyRien
description: Discord bot that bridge chat from minecraft to discord

main: us.cyrien.MineCordBotV1.main.MineCordBot

commands:
    minecordbot:
        description: MineCordBot general commands
        usage: /CFA <command>
    dcmd:
        description: Do Discord commands from Minecraft
        usage: /dcmd <command>
permmission:
    minecordbot.reload:
        default: op
    minecordbot.dcmd:
        default: op